name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    env:
      TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -no-color -input=false

      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve -input=false -no-color